microcontroller:
  idmcu: 1 # id of mcu 
  namespace: "subsys1" # namespace
  generate_library_Path: "Arduino"  # path for generate library
  connection:
    type: "UART"   # ["UART","UDP"] 
    serial_port: "/dev/serial/by-id/usb-Arduino__www.arduino.cc__0043_75330303035351A07101-if00"  # for Serial UART subsystem 1"
    baudrate: 57620  # for UART
    ip_address_mcu: ""  # for UDP example "192.168.1.xx"
    udp_port_mcu: 0  # for UDP


ros: # setup ros is reference from microcontroller example publisher is mean microcontroller publish to ros network
  publisher:  [                           ]
  subscriber: [
    [1, "thumb_finger_R", "std_msgs/Int16.msg"],
    [2, "index_finger_R", "std_msgs/Int16.msg"],
    [3, "middle_finger_R", "std_msgs/Int16.msg"],
    [4, "ring_finger_R", "std_msgs/Int16.msg"],
    [5, "pinky_finger_R", "std_msgs/Int16.msg"],
    [6, "bicep_R", "std_msgs/Int16.msg"],
    [7, "rotate_R", "std_msgs/Int16.msg"],
    [8, "shoulder_R", "std_msgs/Int16.msg"],
    [9, "omoplate_R", "std_msgs/Int16.msg"]    
  ]
  srv_client: [                           ]
  srv_server: [                           ]
  action_client: [                        ]
  action_server: [                        ]
